apiVersion: v1
kind: Pod
metadata:
  name: workload-identity-test
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  containers:
  - image: google/cloud-sdk:alpine
    name: workload-identity-test
    command: ["sleep","infinity"]

# kubectl exec -it workload-identity-test -n flux-system -- sh -c 'curl -H "Metadata-Flavor: Google" http://169.254.169.254/computeMetadata/v1/instance/service-accounts/'
# default/
# flux-sops-client@dat-homelab.iam.gserviceaccount.com/
