---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 24h
  url: https://grafana.github.io/helm-charts
  timeout: 3m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 12h
  maxHistory: 2
  chart:
    spec:
      chart: grafana
      version: 6.17.5
      sourceRef:
        kind: HelmRepository
        name: grafana 1679759908
        namespace: monitoring
  values:
    adminPassword: ${admin_password}
    testFramework:
      enabled: false
    serviceMonitor:
      enabled: false
    deploymentStrategy:
      type: Recreate
    env:
      GF_EXPLORE_ENABLED: true
      GF_PANELS_DISABLE_SANITIZE_HTML: true
      GF_LOG_FILTERS: rendering:debug
    grafana.ini:
      plugins:
        allow_loading_unsigned_plugins: doitintl-bigquery-datasource
    plugins:
      - https://github.com/doitintl/bigquery-grafana/archive/2.0.2.zip;doit-bigquery-datasource
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Google BigQuery
            type: doitintl-bigquery-datasource
            access: proxy
            isDefault: true
            jsonData:
              authenticationType: gce
              defaultProject: dat-homelab
              processingLocation: US
            version: 2
            readOnly: false

  postRenderers:
      - kustomize:
          patchesStrategicMerge:
            - kind: ServiceAccount
              apiVersion: v1
              metadata:
                name: grafana
                namespace: monitoring
                annotations:
                  iam.gke.io/gcp-service-account: "grafana-bigquery-reader@dat-homelab.iam.gserviceaccount.com"
