
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - secrets.enc.yaml
  - helm-release.yaml

generatorOptions:
 disableNameSuffixHash: true

configMapGenerator:
- name: dashboard-gcp-cost
  files:
    - gcp_cost.json=./dashboards/gcp_cost.json
