---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    iam.gke.io/gcp-service-account: "grafana-bigquery-reader@dat-homelab.iam.gserviceaccount.com"
