apiVersion: v1
stringData:
    admin_password: ENC[AES256_GCM,data:cumOYEQWh2rT,iv:z/r7rBEokK2ZtdxjEY84C0cEcE3gOwGi4EKmqb68cIk=,tag:1HdtH57eLa/vXWlsvf6Jhw==,type:str]
kind: Secret
metadata:
    name: grafana-secrets
    namespace: monitoring
type: Opaque
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/dat-home-infra/locations/us-central1/keyRings/sops-vault/cryptoKeys/flux-key
          created_at: "2021-11-16T08:29:33Z"
          enc: CiQAOh7DlRBnvwgwvGQX4kMqpWuM2G6HXKqRCB1OPbJD6BPRNb8SSQAG4LLMRw8Z/vugVOBrlnWvjogoRlqC0Eqn4SRe6WGsU6QPoleeuEc5uJ44o1brJkAS7VR4d/bkoGhJTp0tFdidaI5jLo95fq4=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-16T08:29:34Z"
    mac: ENC[AES256_GCM,data:IeSozp9fqejCJNKi9saQqn24w+14BiKGc00qz+V56wz/B0dpvM6P7Nc9gTpkNtWYldaC1JTvc7lIfoTNmx0MAp+Q9khAkfG/oCWLY9tnIdb+Qd3RLJ3eKXSoaZ4AO+oXYtV814wGV4/LEPFhdFfCwA/JmuS2h+KLWnvBOBaOVM0=,iv:XlGfEzaHaKSxjHoVwq798z2cczVFb/aoDhx4/38Ic9w=,tag:0kVZzeji6Je0H9iUnyD5Tg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
