adminPassword: testpassword

testFramework:
  enabled: false
serviceMonitor:
  enabled: false
deploymentStrategy:
  type: Recreate
env:
  GF_EXPLORE_ENABLED: true
  GF_PANELS_DISABLE_SANITIZE_HTML: true
  GF_LOG_FILTERS: rendering:debug
# persistence:
#   enabled: true
#   size: 2Gi
#   accessModes:
#   - ReadWriteOnce
grafana.ini:
  plugins:
    allow_loading_unsigned_plugins: doitintl-bigquery-datasource
plugins:
  - https://github.com/doitintl/bigquery-grafana/archive/2.0.2.zip;doit-bigquery-datasource
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Google BigQuery
        type: doitintl-bigquery-datasource
        access: proxy
        isDefault: true
        jsonData:
          authenticationType: gce
          defaultProject: dat-homelab
          processingLocation: US
        version: 2
        readOnly: false
