---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kustomize-controller
  namespace: flux-system
  annotations:
    iam.gke.io/gcp-service-account: "flux-sops@dat-home-infra.iam.gserviceaccount.com"
---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
  labels:
    istio-injection: enabled
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  decryption:
    provider: sops
