---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kustomize-controller
  namespace: flux-system
  annotations:
    iam.gke.io/gcp-service-account: "flux-sops-client@dat-homelab.iam.gserviceaccount.com"
---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
  labels:
    istio-injection: enabled
