apiVersion: v1
stringData:
    GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:ixfphTg+3/Ppl+idnBAijIssA19u,iv:1alY3xHE6fokoiAU5IRibotUxEAjWAoXJHUFd00CmPo=,tag:XD85Kv6c7XkXv1Gg3f5/hg==,type:str]
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/dat-homelab/locations/global/keyRings/testbed-keychain/cryptoKeys/sops-key
          created_at: "2021-11-14T05:39:05Z"
          enc: CiQAPU4iNXgqU79xirBlfmPC5kLAqo3WpI2hmL6qis/QIUIQGLMSSQDiIoNL4gLG6+Q1loyFekB9khn5aEee3Fa9NPuucYD/YcmfHJie6pgDLt18d6pCtzhn2cTf4bMvrR4+IjjNhKauC5fCRI9VkGE=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-14T05:39:05Z"
    mac: ENC[AES256_GCM,data:eb11hfc5xY9F+Qxw5R2fEelFFCs+gobrKU462hFFPx3apO19rV633bYP5/iK7a930SZ/VWESav+XB5ZveQEOySQVKZOLD6+zfumDT4+LaTT83ZyJyceY9NAF3eHu5xwr3LxjQ5d6A3evq63PpfxOLpZklsZEbbslVZoA3ZdIAmE=,iv:2QyDJiXjQKRDr5Yhc4Yk+boqaNd225qZ0sjocIUn3DQ=,tag:j8c2RaWtW8AhFasbB/wRsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
