{
 "title": "Google Cloud Billing Costs",
 "description": "Display your Google Cloud Platform billing costs straight from BigQuery.",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "SELECT DISTINCT project.id FROM `$source_project.$source_dataset.$source_table`"
   },
   { "name": "source_project", "label": "Source Project", "query": "trustpath-dataeng" },
   { "name": "source_dataset", "label": "Source Dataset", "query": "zscaler_billing" },
   {
    "name": "source_table",
    "label": "Source Table",
    "query": "gcp_billing_export_v1_01DC76_D7550B_6F531E"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "zscaler_billing.gcp_billing_export_v1_01DC76_D7550B_6F531E ",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "trustpath-dataeng",
     "rawSql": "#standardsql\nSELECT\n  CURRENT_TIMESTAMP() AS time,\n  SUM(cost) AS value\nFROM\n  `$source_project.$source_dataset.$source_table`\nWHERE\n  $__timeFilter(usage_start_time) AND\n  project.id IN ($project)\nGROUP BY 1\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "Project Breakdown",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "#standardsql\nSELECT\n  project.id AS metric,\n  SUM(cost) AS value\nFROM\n  `$source_project.$source_dataset.$source_table`\nWHERE\n  $__timeFilter(usage_start_time)\n  AND project.id IN ($project)\nGROUP BY metric\nORDER BY value DESC"
    }
   ]
  },
  {
   "title": "Top 5 Service Breakdown",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "orderByCol": "1",
     "orderBySort": "1",
     "rawSql": "#standardsql\nSELECT\n  IF(pos > 5, 'Other', metric) AS metric,\n  SUM(value) AS value\nFROM (\n  SELECT\n    service.description AS metric,\n    SUM(cost) AS value,\n    ROW_NUMBER() OVER (ORDER BY SUM(cost) DESC) AS pos\n  FROM\n    `$source_project.$source_dataset.$source_table`\n  WHERE\n    $__timeFilter(usage_start_time)\n    AND project.id IN ($project)\n  GROUP BY 1\n)\nGROUP BY metric\nORDER BY metric != 'Other' DESC, value DESC"
    }
   ]
  },
  {
   "title": "Service Breakdown",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "dataset": "zscaler_billing.gcp_billing_export_v1_01DC76_D7550B_6F531E ",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "trustpath-dataeng",
     "rawSql": "#standardsql\nSELECT *\nFROM (\n  SELECT\n    $__timeGroup(usage_start_time, 1d),\n    service.description AS metric,\n    SUM(cost) AS value\n  FROM\n    `$source_project.$source_dataset.$source_table`\n  WHERE\n    $__timeFilter(usage_start_time) \n    AND project.id IN ($project)\n  GROUP BY 1, 2\n  ORDER BY 1 ASC\n)\nWHERE value > 0"
    }
   ]
  },
  {
   "title": "SKU Breakdown",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD", "label": "Cost ($)" }
   ],
   "targets": [
    {
     "dataset": "zscaler_billing.gcp_billing_export_v1_01DC76_D7550B_6F531E ",
     "orderByCol": "1",
     "orderBySort": "1",
     "project": "trustpath-dataeng",
     "rawSql": "#standardsql\nSELECT * FROM (\n  SELECT\n    $__timeGroup(usage_start_time, 1d),\n    IFNULL(sku.description, '_') AS metric,\n    SUM(cost) AS value\n  FROM `$source_project.$source_dataset.$source_table`\n  WHERE\n    DATE(usage_start_time) >= DATE($__millisTimeFrom(_)) AND\n    DATE(usage_start_time) < DATE($__millisTimeTo(_)) AND\n    project.id IN ($project)\n  GROUP BY 1, 2\n  ORDER BY 1, 2\n)\nWHERE value >= 1"
    }
   ]
  },
  {
   "title": "Breakdown by Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "type": "piechart",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "dataset": "zscaler_billing",
       "orderByCol": "1",
       "orderBySort": "1",
       "project": "trustpath-dataeng",
       "rawSql": "SELECT\n  time_column,\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "type": "graph",
     "gridPos": { "h": 12, "w": 17, "x": 7, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "yaxes": [
      { "format": "currencyUSD", "label": "Cost ($)" }
     ],
     "targets": [
      {
       "dataset": "zscaler_billing",
       "orderByCol": "1",
       "orderBySort": "1",
       "project": "trustpath-dataeng",
       "rawSql": "-- $__millisTimeFrom(usage_start_time) // $__millisTimeTo(_)\nSELECT\n  $__timeGroupAlias(usage_start_time, 1d),\n  IFNULL(service.description, '_') AS metric,\n  SUM(cost) AS value\nFROM `$table_billing`\nWHERE\n  DATE(usage_start_time) >= DATE($__millisTimeFrom(_)) AND\n  DATE(usage_start_time) < DATE($__millisTimeTo(_)) AND\n  project.id IN ($project)\nGROUP BY 1, 2\nORDER BY 1, 2"
      }
     ]
    }
   ]
  }
 ]
}